# Generated by Django 4.2 on 2023-05-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatoficer',
            name='beat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='beat_officer', to='app.bearareamodel'),
            preserve_default=False,
        ),
    ]
