# Generated by Django 4.2 on 2023-05-03 10:23

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(default='', max_length=13, validators=[base.validators.validate_phone_no]),
            preserve_default=False,
        ),
    ]
