# Generated by Django 4.2 on 2023-05-03 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import report.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(upload_to='report')),
                ('audio', models.FileField(blank=True, null=True, upload_to=None)),
                ('comment', models.TextField(blank=True, null=True)),
                ('priority', models.FloatField(default=5, validators=[report.validators.validate_stars])),
                ('bo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_officer_report', to='authentication.usermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
