# Generated by Django 4.2 on 2023-05-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivisionmodel',
            name='dysp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dysp', to='authentication.usermodel'),
        ),
        migrations.AddField(
            model_name='policeareamodel',
            name='pi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pi', to='authentication.usermodel'),
        ),
        migrations.AddField(
            model_name='policeareamodel',
            name='sub_div',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_station_region', to='app.subdivisionmodel'),
        ),
        migrations.AddField(
            model_name='locaitonsmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_type', to='app.categorymodel'),
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='sp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sp', to='authentication.usermodel'),
        ),
        migrations.AddField(
            model_name='bearareamodel',
            name='sub_div',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_area', to='app.subdivisionmodel'),
        ),
    ]
